### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by numberZero** [LibreBlockGame/GameToBeRenamed#2]
Minetest claims to be an engine, not a game. It is neither, actually. IMO it is more of a *platform* that lets one play different voxel games. So is this a game, a platform, an engine, something else?

**Comment by ChargingBulle** [comment]
Hi @numberZero I have described my vision here:

https://github.com/minetest/minetest/issues/11657#issuecomment-988034266

This github repo is for collecting potential names for a rebranding. See #1. In the future i might work a few days a week on the project and/or hire 1-2 people to work together with me. But those are all bridges we have not yet to cross b/c we haven't come to them yet.

_Why_ a name change is important for the community I have written in great detail here:

https://github.com/minetest/minetest/issues/11657#issuecomment-985730480

Did I answer your question? Feel free to contact me and/or propose names and/or send a small message for hiring considerations

**Comment by ChargingBulle** [comment]
See also: https://github.com/minetest/minetest/issues/9028#issuecomment-1170750022
